num_drones: 20
model: iris
initial_positions:
  "1":  { initial_pose: { x: 0 , y: 0 } }
  "2":  { initial_pose: { x: 2 , y: 0 } }
  "3":  { initial_pose: { x: 4 , y: 0 } }
  "4":  { initial_pose: { x: 6 , y: 0 } }
  "5":  { initial_pose: { x: 8 , y: 0 } }
  "6":  { initial_pose: { x: 0 , y: 2 } }
  "7":  { initial_pose: { x: 2 , y: 2 } }
  "8":  { initial_pose: { x: 4 , y: 2 } }
  "9":  { initial_pose: { x: 6 , y: 2 } }
  "10": { initial_pose: { x: 8 , y: 2 } }
  "11": { initial_pose: { x: 0 , y: 4 } }
  "12": { initial_pose: { x: 2 , y: 4 } }
  "13": { initial_pose: { x: 4 , y: 4 } }
  "14": { initial_pose: { x: 6 , y: 4 } }
  "15": { initial_pose: { x: 8 , y: 4 } }
  "16": { initial_pose: { x: 0 , y: 6 } }
  "17": { initial_pose: { x: 2 , y: 6 } }
  "18": { initial_pose: { x: 4 , y: 6 } }
  "19": { initial_pose: { x: 6 , y: 6 } }
  "20": { initial_pose: { x: 8 , y: 6 } }

# Required for lat/lon -> local conversion
geo_origin:
  lat: 22.126857331924786
  lon: 95.12503864452775
  alt: 0.0